# Generated by Django 4.2.4 on 2023-09-11 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
