# Generated by Django 4.2.4 on 2023-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_catalog_price_alter_catalog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='picture',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
